domain: github.io
url: https://yoviajo.github.io/
baseurl: "/wind"

title: Portafolio Eric Armijo
email: rcrmj@hotmail.com
author: Eric Armijo

lang: es

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "rcrmj@hotmail.com"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
